-- Migration: 0001_init_auth_users
-- Initial schema for the `auth.users` table consumed by features/auth.
--
-- Constraint names `users_email_key` and `users_username_key` are part of the
-- API contract: PostgresUserRepository.mapUniqueViolation matches on them to
-- translate SQLSTATE 23505 into EMAIL_TAKEN / USERNAME_TAKEN.
--
-- DO NOT edit this file after it has been applied to any environment.
-- Schema changes go into a new file (e.g. 0002_*.sql).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS auth;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'user_status'
          AND n.nspname = 'auth'
    ) THEN
        CREATE TYPE auth.user_status AS ENUM ('active', 'banned', 'deleted', 'pending');
    END IF;
END
$$;

CREATE TABLE auth.users (
    id                       UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
    login                    VARCHAR(255)     NOT NULL,
    password_hash            VARCHAR(255)     NOT NULL,
    email                    VARCHAR(255)     NOT NULL,
    email_confirmed_at       TIMESTAMPTZ      NULL,
    username                 VARCHAR(255)     NOT NULL,
    display_name             VARCHAR(255)     NOT NULL,
    last_sign_in_at          TIMESTAMPTZ      NULL,
    created_at               TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    confirmation_token       VARCHAR(255)     NULL,
    confirmation_sent_at     TIMESTAMPTZ      NULL,
    phone                    TEXT             NULL,
    phone_confirmed_at       TIMESTAMPTZ      NULL,
    deleted_at               TIMESTAMPTZ      NULL,
    reauthentication_token   VARCHAR(255)     NULL DEFAULT '',
    reauthentication_sent_at TIMESTAMPTZ      NULL,
    banned_until             TIMESTAMPTZ      NULL,
    status                   auth.user_status NOT NULL DEFAULT 'pending',
    CONSTRAINT users_email_key    UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_login_key    UNIQUE (login)
);
