-- Migration: 0002_init_auth_sessions
-- Server-side sessions for opaque bearer tokens.
--
-- Each row is one active or expired session for a user. The raw token is
-- never stored — only its SHA-256 hash, so a database leak does not give an
-- attacker usable tokens. Lookups happen by `token_hash` on every
-- authenticated request, which is why it is UNIQUE (and therefore indexed).
--
-- ON DELETE CASCADE wipes a user's sessions if the user is removed, so we
-- never have orphan sessions referencing a missing auth.users row.
--
-- Reserved for the upcoming flow:
--   * "logout from all devices" — DELETE WHERE user_id = ? (user_id index).
--   * Periodic cleanup — DELETE WHERE expires_at < NOW() (cheap full scan
--     today; add an expires_at index when traffic justifies it).
--
-- DO NOT edit this file after it has been applied to any environment.
-- Schema changes go into a new file (e.g. 0003_*.sql).

CREATE TABLE auth.sessions (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT sessions_token_hash_key UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON auth.sessions (user_id);
